# Generated by Django 6.0.3 on 2026-05-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0003_category_subscribers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                through="News.PostCategory",
                to="News.category",
                verbose_name="Категория",
            ),
        ),
    ]
